### ISSUE TITLE
npm install error with OSX 10.14.1

### ISSUE THREAD

**Issue by vrminds** [enigmampc/enigma-template-dapp#3]
After installing npm in the /client folder I got the following message: "run install react-script 2.1.1"

Installing version 2.1.1 instead of 1.2.2 lead to another issue with conflicting webpack versions:
<img width="598" alt="screenshot1" src="https://user-images.githubusercontent.com/24575438/50166979-631ca280-02e8-11e9-89ff-362050c281f1.png">
<img width="805" alt="screenshot2" src="https://user-images.githubusercontent.com/24575438/50166984-657efc80-02e8-11e9-93c6-18ed1c535206.png">

I followed the steps described above, but it did not resolve the issue. Any idea?

**Comment by apalepu23** [comment]
hmm, haven't seen this before, happy to work with you to debug the issue though! looks like you may be running into a similar issue as this: https://github.com/facebook/create-react-app/issues/5901

Does that look to be the same thing, and if so, maybe that solution would work? Keep me posted!

**Comment by vrminds** [comment]
thanks for the quick answer. It looks similar, I'll have a look.

**Comment by vrminds** [comment]
I don't have `node-modules` installed in the home folder as described in the linked post.
Nevertheless when I delete `/enigma-template-dapp/node_modules/webpack` the app opens in the browser with the error that webpack is required. 

There are two conflicting webpack versions:
webpack 4.16.0 in `/enigma-template-dapp/node_modules/webpack`
webpack 4.19.1 in `/enigma-template-dapp/client/node_modules/webpack`

**Comment by apalepu23** [comment]
Hey! This should now be resolved - the eth-crypto package in the root folder installs a different version of webpack that causes the react-scripts installed version of webpack to fail. Please pull the updated repo and try to relaunch everything and let me know how that goes :)

**Comment by vrminds** [comment]
hey, it works now! Thank you
